(function(){
const cfg=window.SUNBOT_TELEMETRY_CONFIG||{};if(cfg.enabled===false)return;
const q=new URLSearchParams(location.search);const now=()=>new Date().toISOString();
function rid(k){let v=localStorage.getItem(k);if(!v){v=(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now());localStorage.setItem(k,v)}return v}
const visitorId=rid('sunbot_visitor_id');let sessionId=sessionStorage.getItem('sunbot_session_id');if(!sessionId){sessionId=(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now());sessionStorage.setItem('sunbot_session_id',sessionId)}
const ctx={visitor_id:visitorId,session_id:sessionId,link_id:q.get('lid')||q.get('link_id')||'',school:q.get('school')||'',school_id:q.get('school_id')||'',audience:q.get('audience')||document.body.dataset.audience||'common',source:q.get('source')||'',asset_type:q.get('asset')||'',asset_version:q.get('ver')||'',campaign:q.get('campaign')||'',entry_from:q.get('from')||'',page_path:location.pathname,page_type:location.pathname.includes('/survey/')?'survey':location.pathname.includes('/catalogue/')?'catalogue':'profile',referrer:document.referrer||'',viewport:innerWidth+'x'+innerHeight,user_agent_class:/Mobile|Android|iPhone/i.test(navigator.userAgent)?'mobile':'desktop',attribution_type:(q.get('lid')||q.get('link_id')||q.get('school')||q.get('school_id'))?'LINK_ATTRIBUTED':'ANONYMOUS',consent_mode:'ESSENTIAL_B2B_ANALYTICS'};
let queue=JSON.parse(localStorage.getItem('sunbot_telemetry_queue')||'[]');
function persist(){localStorage.setItem('sunbot_telemetry_queue',JSON.stringify(queue.slice(-500)))}
async function send(type,payload){const item={type,payload:{...ctx,...payload,ts:payload&&payload.ts||now()}};if(!cfg.endpoint){queue.push(item);persist();return false}try{await fetch(cfg.endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(item),keepalive:true});return true}catch(e){queue.push(item);persist();return false}}
async function flush(){if(!cfg.endpoint||!queue.length)return;const copy=[...queue];queue=[];persist();for(const item of copy){try{await fetch(cfg.endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(item),keepalive:true})}catch(e){queue.push(item)}}persist()}
window.SunbotTelemetry={event:(name,extra={})=>send('event',{event_name:name,...extra}),draft:(payload)=>send('draft',payload),submit:(payload)=>send('submit',payload),signal:(payload)=>send('signal',payload),flush,context:ctx};
flush();send('event',{event_name:'page_view'});
let maxDepth=0;let sectionStart=Date.now();let currentSection='';
function depth(){const d=Math.round((scrollY+innerHeight)/Math.max(document.documentElement.scrollHeight,1)*100);if(d>maxDepth){maxDepth=d;if([25,50,75,90].some(x=>d>=x&&maxDepth<x+5))send('event',{event_name:'scroll_depth',scroll_depth:d})}}
addEventListener('scroll',depth,{passive:true});
if('IntersectionObserver'in window){const seen={};const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const id=e.target.id||e.target.dataset.step||e.target.dataset.model||e.target.querySelector('h2,h3')?.textContent?.trim()||'section';if(currentSection&&currentSection!==id)send('event',{event_name:'section_exit',section_id:currentSection,dwell_ms:Date.now()-sectionStart});currentSection=id;sectionStart=Date.now();if(!seen[id]){seen[id]=1;send('event',{event_name:'section_view',section_id:id,item_label:e.target.querySelector('h2,h3')?.textContent?.trim()||''})}}}),{threshold:.45});document.querySelectorAll('section,[data-step],[data-model-detail]').forEach(x=>obs.observe(x))}
document.addEventListener('click',e=>{const a=e.target.closest('a,button,summary');if(!a)return;const label=(a.textContent||'').trim().slice(0,140);let name='click';if(a.closest('[data-model-detail]')||a.closest('details'))name='model_open';else if(a.href||a.matches('button'))name='cta_click';send('event',{event_name:name,item_label:label,item_id:a.dataset.model||a.id||''})},true);
// Preserve attribution parameters through the Sunbot digital journey.
function preserve(){const keep=['lid','link_id','school','school_id','audience','source','asset','ver','campaign'];document.querySelectorAll('a[href]').forEach(a=>{try{const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;if(!/\/(profile-v2|catalogue|survey)\//.test(u.pathname))return;keep.forEach(k=>{const v=q.get(k);if(v&&!u.searchParams.has(k))u.searchParams.set(k,v)});if(!u.searchParams.has('from'))u.searchParams.set('from',ctx.page_type);a.href=u.pathname+u.search+u.hash}catch(e){}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',preserve);else preserve();setTimeout(preserve,250);
addEventListener('pagehide',()=>{if(currentSection)send('event',{event_name:'section_exit',section_id:currentSection,dwell_ms:Date.now()-sectionStart,scroll_depth:maxDepth});send('event',{event_name:'page_exit',scroll_depth:maxDepth})});
})();