(function(){
const params=new URLSearchParams(location.search);const audience=params.get('audience')||'common';const guided=params.get('guided')==='1'&&audience!=='common';const school=params.get('school')||'';const source=params.get('source')||'';const sender=params.get('sender')||'';const senderEmail=params.get('sender_email')||'';const body=document.body;body.dataset.audience=audience;body.classList.add('aud-'+audience);
const config={
common:{label:'Catalogue chung',title:'Mỗi nhà trường có thể bắt đầu với Sunbot theo một cách khác nhau.',lead:'Từ tổ chức lớp học trực tiếp, đào tạo giáo viên, chuyển giao chương trình đến STEAM Corner, STEAM Lab, Camp, Day và triển khai theo hệ thống – Sunbot cùng nhà trường lựa chọn phương án phù hợp với mục tiêu giáo dục và nguồn lực thực tế.',guidedTitle:'Chọn cách hợp tác phù hợp với mục tiêu của nhà trường.',guidedLead:'Ba hướng dưới đây giúp nhà trường nhanh chóng xác định nhóm mô hình nên xem trước.',recommended:[1,2,3],cards:[['Muốn triển khai nhanh','Sunbot trực tiếp tổ chức giảng dạy giúp nhà trường bắt đầu nhanh với chương trình, giáo viên và học liệu đồng bộ.',1],['Muốn giáo viên trường làm chủ','Đào tạo giáo viên và chuyển giao giúp nhà trường xây năng lực nội bộ và triển khai ổn định lâu dài.',2],['Muốn mở rộng quy mô','Mô hình cụm hoặc hệ thống phù hợp khi cần triển khai thống nhất trên nhiều cơ sở hoặc điểm trường.',8]]},
public:{label:'Dành cho trường mầm non công lập',title:'Các cách hợp tác phù hợp với định hướng và nguồn lực của trường mầm non công lập.',lead:'Sunbot có thể đồng hành từ đào tạo giáo viên, chuyển giao chương trình, STEAM Corner/STEAM Lab đến triển khai theo cụm hoặc nhiều điểm trường. Nhà trường có thể lựa chọn mô hình phù hợp với mục tiêu giáo dục, đội ngũ và điều kiện thực tế.',guidedTitle:'Với trường công lập, có thể bắt đầu từ ba hướng: phát triển đội ngũ, đầu tư không gian hoặc triển khai theo nhiều điểm trường.',guidedLead:'Mỗi hướng có thể được điều chỉnh theo quy mô, đội ngũ giáo viên và kế hoạch phát triển của nhà trường.',recommended:[2,3,4,5,8],cards:[['Phát triển năng lực giáo viên','Đào tạo giáo viên nhà trường giúp đội ngũ từng bước làm chủ phương pháp, thiết bị và cách tổ chức lớp Sunbot.',2],['Tạo không gian giáo dục công nghệ','STEAM Corner phù hợp để bắt đầu gọn; STEAM Lab tạo một không gian trải nghiệm chuyên biệt khi nhà trường muốn đầu tư dài hạn.',4],['Triển khai nhiều điểm trường','Mô hình cụm hoặc hệ thống giúp thống nhất chương trình, đào tạo và chất lượng trên nhiều điểm triển khai.',8]]},
private:{label:'Dành cho trường mầm non tư thục',title:'Các cách hợp tác giúp trường tư tạo khác biệt giáo dục và phát triển bền vững.',lead:'Sunbot có thể đồng hành từ lớp học trực tiếp, Camp, Day, Corner/Lab đến đào tạo và chuyển giao. Nhà trường có thể bắt đầu nhanh để tạo trải nghiệm, sau đó nâng dần mức độ chủ động khi chương trình phát triển.',guidedTitle:'Với trường tư, có thể chọn mô hình theo ba mục tiêu: triển khai nhanh, xây đội ngũ hoặc tạo điểm nhấn khác biệt.',guidedLead:'Các mô hình có thể kết hợp linh hoạt theo chiến lược chương trình, tuyển sinh và đầu tư của từng trường.',recommended:[1,2,3,4,5,6,7],cards:[['Muốn triển khai nhanh','Sunbot trực tiếp tổ chức giảng dạy phù hợp khi trường muốn bắt đầu sớm với một chương trình hoàn chỉnh.',1],['Muốn giáo viên trường làm chủ','Đào tạo giáo viên và chuyển giao giúp xây năng lực vận hành lâu dài ngay trong nhà trường.',2],['Muốn tạo trải nghiệm nổi bật','Camp, Day, Corner hoặc Lab có thể tạo điểm nhấn rõ ràng cho trẻ, phụ huynh và môi trường giáo dục của trường.',6]]},
system:{label:'Dành cho hệ thống trường',title:'Các cách triển khai giúp nhiều cơ sở cùng một chuẩn nhưng vẫn linh hoạt tại từng điểm.',lead:'Sunbot hỗ trợ hệ thống chuẩn hóa chương trình, đào tạo, thiết bị và cách tổ chức triển khai, đồng thời cho phép điều chỉnh phù hợp với điều kiện của từng cơ sở.',guidedTitle:'Với hệ thống trường, nên xem trước các mô hình có khả năng chuẩn hóa và mở rộng.',guidedLead:'Đào tạo, chuyển giao và triển khai theo cụm/hệ thống là trục chính; Corner/Lab có thể được cấu hình theo từng cơ sở.',recommended:[2,3,5,8],cards:[['Chuẩn hóa đội ngũ','Đào tạo theo một chuẩn chung giúp giáo viên tại các cơ sở có cùng cách tổ chức và phát triển chương trình.',2],['Chuẩn hóa chương trình','Chuyển giao theo chuẩn Sunbot giúp hệ thống chủ động triển khai lâu dài mà vẫn duy trì tính nhất quán.',3],['Mở rộng nhiều cơ sở','Mô hình cụm/hệ thống giúp triển khai theo lộ trình, với một chuẩn chuyên môn chung cho nhiều điểm trường.',8]]}
};const d=config[audience]||config.common;
function contextParams(){const q=new URLSearchParams();if(audience!=='common')q.set('audience',audience);if(guided)q.set('guided','1');if(school)q.set('school',school);if(sender)q.set('sender',sender);if(senderEmail)q.set('sender_email',senderEmail);if(source)q.set('source',source);return q}
if(guided){document.querySelector('#audience-chip').hidden=false;document.querySelector('#audience-chip').textContent=school?`${d.label} · ${school}`:d.label}document.querySelector('#hero-title').textContent=d.title;document.querySelector('#hero-lead').textContent=d.lead;document.querySelector('#guided-title').textContent=d.guidedTitle;document.querySelector('#guided-lead').textContent=d.guidedLead;document.querySelector('#nav-subtitle').textContent=sender?`${d.label} · Đồng hành: ${sender}`:d.label;document.querySelector('#guided-grid').innerHTML=d.cards.map(c=>`<article class="guided-card"><strong>${escapeHtml(c[0])}</strong><p>${escapeHtml(c[1])}</p><a href="#m${c[2]}">Xem mô hình phù hợp →</a></article>`).join('');d.recommended.forEach(id=>{document.querySelectorAll(`[data-model="${id}"]`).forEach(el=>el.classList.add('recommended'));const detail=document.querySelector(`[data-model-detail="${id}"]`);if(detail)detail.classList.add('recommended-detail');const row=document.querySelector(`[data-row-model="${id}"]`);if(row)row.classList.add('recommended-row')});
const qp=contextParams();const suffix=qp.toString()?'?'+qp.toString():'';const backUrl='../profile-v2/'+suffix;['profile-back','profile-back-top','profile-back-bottom'].forEach(id=>{const el=document.getElementById(id);if(el)el.href=backUrl});const surveyUrl='../survey/'+suffix;[...document.querySelectorAll('.dark .actions')].forEach(area=>{if(area.querySelector('[data-survey-link]'))return;const link=document.createElement('a');link.className='btn primary';link.href=surveyUrl;link.dataset.surveyLink='1';link.textContent=guided?'Trao đổi nhu cầu của nhà trường →':'Chia sẻ nhu cầu với Sunbot →';area.prepend(link)});[...document.querySelectorAll('a[href*="survey"],a[data-survey-link]')].forEach(x=>x.href=surveyUrl);if(guided){const first=d.recommended[0];const detail=document.querySelector(`[data-model-detail="${first}"]`);if(detail)detail.open=true}function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
})();
(function(){
const intro=document.querySelector('.intro-band');if(!intro||document.querySelector('.trust-ribbon'))return;
const style=document.createElement('style');style.textContent=`
.trust-ribbon{padding:18px 0;background:#fff;border-bottom:1px solid var(--line)}
.trust-ribbon-inner{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:18px 22px;border:1px solid color-mix(in srgb,var(--accent) 18%,var(--line));border-radius:20px;background:linear-gradient(120deg,var(--accent-soft),#fff 58%,#f7f9fc);box-shadow:0 10px 28px rgba(24,32,51,.045)}
.trust-ribbon-kicker{display:inline-flex;align-items:center;justify-content:center;width:42px;height:42px;border-radius:14px;background:var(--accent);color:#fff;font-size:18px;font-weight:900;box-shadow:0 8px 20px color-mix(in srgb,var(--accent) 24%,transparent)}
.trust-ribbon-copy{min-width:0}.trust-ribbon-copy strong{display:block;font-size:14px;color:var(--ink);margin-bottom:3px}.trust-ribbon-copy p{margin:0;font-size:12px;color:var(--muted);line-height:1.55}.trust-ribbon-proof{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.trust-ribbon-proof span{display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;background:#fff;border:1px solid var(--line);font-size:10px;font-weight:800;color:#475467;white-space:nowrap}
@media(max-width:900px){.trust-ribbon-inner{grid-template-columns:auto 1fr}.trust-ribbon-proof{grid-column:1/-1;justify-content:flex-start;padding-left:60px}}
@media(max-width:600px){.trust-ribbon{padding:14px 0}.trust-ribbon-inner{grid-template-columns:1fr;padding:17px;gap:10px}.trust-ribbon-kicker{width:38px;height:38px}.trust-ribbon-proof{grid-column:auto;padding-left:0;justify-content:flex-start}.trust-ribbon-proof span{font-size:9px;padding:6px 8px}}
`;document.head.appendChild(style);
const ribbon=document.createElement('section');ribbon.className='trust-ribbon';ribbon.setAttribute('aria-label','Nền tảng tin cậy của Sunbot');ribbon.innerHTML=`<div class="container"><div class="trust-ribbon-inner"><div class="trust-ribbon-kicker">✓</div><div class="trust-ribbon-copy"><strong>Nền tảng chuyên môn được xây dựng và kiểm chứng qua nhiều năm</strong><p>Sunbot kết hợp thẩm định chuyên môn, kinh nghiệm triển khai thực tế và sự ghi nhận trong hệ sinh thái EdTech khu vực.</p></div><div class="trust-ribbon-proof"><span>IPD · 2019</span><span>VNIES · 2020</span><span>HolonIQ SEA EdTech 50 · 2025</span><span>300+ cơ sở trước 2026</span></div></div></div>`;
intro.insertAdjacentElement('afterend',ribbon);
})();
(function(){const c=document.createElement('script');c.src='../telemetry/config.js';c.onload=()=>{const t=document.createElement('script');t.src='../telemetry/client.js';document.head.appendChild(t)};document.head.appendChild(c)})();